import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { getAllFilesMetadata } from '@/lib/mdx'




export default function Home({posts}) {
  return (
    <div className={styles.content}>

      <Head>
        <title>noepm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>mi blog jamstack</h1>
        

        <div className={styles.grid}>
          {posts.map((post) => (
            <Link 
            key={post.slug} 
            href={`/${post.slug}`} >
                  
            <h2 >{post.title}&rarr; </h2>
            <p >{post.date }</p>
          
            </Link>
          ))}           
        </div>
      

      </main>
    </div>
    
  )
}

export async function getStaticProps () {
  const posts = await getAllFilesMetadata();
  console.log(posts);
  return{
    props: {posts},
  };
}
